---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHR0eDYybXV1Cg==
  CLOUDINARY_KEY: NTgyNTMzNDIyMjE1MzMxCg==
  CLOUDINARY_SECRET: QUdVS1hpMzc5M2Fsdnh2cmhjQW5aYlp2NkNzCg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhMkZ5WVc0dGJtVm5hUzB4TWlJc0ltRWlPaUpqYldabU5YZGpOV1V3WkRONk1teHdZbUpzYzNabWFXUmhJbjAuT1NHSVkwS1k0WEMyeldYUFQ1SzdwZwo=
  DB_URL: bW9uZ29kYitzcnY6Ly9rYXJhbjpLYWZrYSU0MCUyM1BETTIyMTJAay1jbG91ZC1tb25nby1kYi5ieHk5NzMwLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1LLUNsb3VkLU1vbmdvLURCCg==
  SECRET: a2FyYW5uZWdpCg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: devopskarannegi/yelp-camp-deployment:v0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 90   # Adjust the initial delay here
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 90   # Adjust the initial delay here
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
